[package]
name = "calcli"
description = "A command line application, that helps you train mental calculation."
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.59", features = ["derive"] }
rand = "0.10.0"
tabled = { version = "0.20.0", features = ["ansi"] }