[package]
name = "calcli"
description = "A command line application, that helps you train mental calculation."
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.38", features = ["derive"] }
rand = "0.9.1"
tabled = { version = "0.19.0", features = ["ansi"] }